// export const LOGIN_REQUEST = 'LOGIN_REQUEST';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const HOME_PAGE_DETAILS_REQUEST = 'HOME_PAGE_DETAILS_REQUEST';
export const HOME_PAGE_DETAILS_SUCCESS = 'HOME_PAGE_DETAILS_SUCCESS';
export const HOME_PAGE_DETAILS_FAILURE = 'HOME_PAGE_DETAILS_FAILURE';
